version: "3"
services:
  server:
    build: ./server
    ports:
      - "5001:5001"
    env_file:
      - ./server/.env
    command: npm run start
  client:
    build: ./client
    ports:
      - "3000:3000"
    environment:
      - REACT_APP_API_URL=http://localhost:5001/api
    depends_on:
      - server
