version: "3"
services:
  server:
    command: npm run start:dev
    volumes:
      - ./server:/server
      - ./server/node_modules:/app/node_modules
  client:
    volumes:
      - ./client:/app/
      - ./client/node_modules:/app/node_modules

