version: "3"
services:
  mongodb:
    image: mongo
    ports:
      - "27017:27017"
  server:
    build: ./server
    ports:
      - "5001:5001"
    environment:
      - API_PORT=5001
      - MONGO_URI=mongodb://mongodb:27017/shop
    command: npm run start
    depends_on:
      - mongodb
  client:
    build: ./client
    ports:
      - "3000:3000"
    environment:
      - REACT_APP_API_URL=http://localhost:5001
      # - CI=true
    depends_on:
      - server
