export const productsData = [
  {
    "id": "prod_Oqvo0SRUh5TzTm",
    "object": "product",
    "active": true,
    "attributes": [],
    "created": 1697790037,
    "default_price": "price_1O3DwfGzrCvGnkrSNlxVzGOF",
    "description":
      "Introducing our space-saving dark small dining table - a stylish solution for compact living. Its rich finish and smart design make it ideal for intimate meals and cozy gatherings, adding a touch of sophistication to your home.",
    "features": [
      {
        "name": "4 Seater",
      },
      {
        "name": "Solid oak",
      },
    ],
    "images": [
      "https://files.stripe.com/links/MDB8YWNjdF8xTnJES3JHenJDdkdua3JTfGZsX3Rlc3RfRzNrN2E5WFBrT25nalZST3QyTVZKeVlS00iAAPh1xH",
    ],
    "livemode": false,
    "metadata": {
      "dining": "table",
    },
    "name": "Aestura Dining Table",
    "package_dimensions": null,
    "shippable": null,
    "statement_descriptor": null,
    "tax_code": null,
    "type": "service",
    "unit_label": null,
    "updated": 1697858298,
    "url": null,
    "price": {
      "id": "price_1O3DwfGzrCvGnkrSNlxVzGOF",
      "object": "price",
      "active": true,
      "billing_scheme": "per_unit",
      "created": 1697790037,
      "currency": "usd",
      "custom_unit_amount": null,
      "livemode": false,
      "lookup_key": null,
      "metadata": {},
      "nickname": null,
      "product": "prod_Oqvo0SRUh5TzTm",
      "recurring": null,
      "tax_behavior": "unspecified",
      "tiers_mode": null,
      "transform_quantity": null,
      "type": "one_time",
      "unit_amount": 45000,
      "unit_amount_decimal": "45000",
    },
  },

  {
    "id": "prod_OqvkhdeyHCW03F",
    "object": "product",
    "active": true,
    "attributes": [],
    "created": 1697789805,
    "default_price": "price_1O3DswGzrCvGnkrS2BbAwRhc",
    "description":
      "Upgrade your dining area with our 4-seater small dining table. Perfect for intimate gatherings, its compact design doesn't compromise on style or functionality. Enjoy meals and conversations in a space-saving and elegant setting.",
    "features": [
      {
        "name": "4 Seater",
      },
    ],
    "images": [
      "https://files.stripe.com/links/MDB8YWNjdF8xTnJES3JHenJDdkdua3JTfGZsX3Rlc3RfSXlFcWhLQ0hiRVF2d3FOVVl5b3RYYU4200AR4WHgQ3",
    ],
    "livemode": false,
    "metadata": {
      "Dining": "table",
    },
    "name": "Barcelona Dining Table",
    "package_dimensions": null,
    "shippable": null,
    "statement_descriptor": null,
    "tax_code": null,
    "type": "service",
    "unit_label": null,
    "updated": 1697858518,
    "url": null,
    "price": {
      "id": "price_1O3DswGzrCvGnkrS2BbAwRhc",
      "object": "price",
      "active": true,
      "billing_scheme": "per_unit",
      "created": 1697789806,
      "currency": "usd",
      "custom_unit_amount": null,
      "livemode": false,
      "lookup_key": null,
      "metadata": {},
      "nickname": null,
      "product": "prod_OqvkhdeyHCW03F",
      "recurring": null,
      "tax_behavior": "unspecified",
      "tiers_mode": null,
      "transform_quantity": null,
      "type": "one_time",
      "unit_amount": 40000,
      "unit_amount_decimal": "40000",
    },
  },
  {
    "id": "prod_OqvjeZvNmSazL7",
    "object": "product",
    "active": true,
    "attributes": [],
    "created": 1697789735,
    "default_price": "price_1O3DroGzrCvGnkrSPvLZFmc8",
    "description":
      "Introducing our 4-seater small dining table, perfect for intimate meals. Compact and stylish, it's ideal for smaller spaces, offering a cozy setting for dining with family or friends while adding a touch of sophistication to your home.",
    "features": [
      {
        "name": "4 Seater",
      },
      {
        "name": "Easy cleaning",
      },
    ],
    "images": [
      "https://files.stripe.com/links/MDB8YWNjdF8xTnJES3JHenJDdkdua3JTfGZsX3Rlc3RfN0hlbDVpZmlrQm9tcU9TdlJzSzJ3U09K00pwMLKYoS",
    ],
    "livemode": false,
    "metadata": {
      "dining": "table",
    },
    "name": "Hillsdale Dining Table",
    "package_dimensions": null,
    "shippable": null,
    "statement_descriptor": null,
    "tax_code": null,
    "type": "service",
    "unit_label": null,
    "updated": 1697844757,
    "url": null,
    "price": {
      "id": "price_1O3DroGzrCvGnkrSPvLZFmc8",
      "object": "price",
      "active": true,
      "billing_scheme": "per_unit",
      "created": 1697789736,
      "currency": "usd",
      "custom_unit_amount": null,
      "livemode": false,
      "lookup_key": null,
      "metadata": {},
      "nickname": null,
      "product": "prod_OqvjeZvNmSazL7",
      "recurring": null,
      "tax_behavior": "unspecified",
      "tiers_mode": null,
      "transform_quantity": null,
      "type": "one_time",
      "unit_amount": 55000,
      "unit_amount_decimal": "55000",
    },
  },
  {
    "id": "prod_Oqvh8kupUP5etR",
    "object": "product",
    "active": true,
    "attributes": [],
    "created": 1697789647,
    "default_price": "price_1O3DqOGzrCvGnkrSgyXzYKAU",
    "description":
      "Elevate your dining area with a modern 4-seater small dining table. Its sleek design and compact size are perfect for urban living, offering a stylish and functional space for intimate meals and gatherings.",
    "features": [
      {
        "name": "Solid wood",
      },
      {
        "name": "Scratch resistant",
      },
    ],
    "images": [
      "https://files.stripe.com/links/MDB8YWNjdF8xTnJES3JHenJDdkdua3JTfGZsX3Rlc3RfWHFIQm91TmNiaENaTjRINzVKbUdUWThp00OFE1rxxM",
    ],
    "livemode": false,
    "metadata": {
      "dining": "tables",
    },
    "name": "Waterford Dining Table",
    "package_dimensions": null,
    "shippable": null,
    "statement_descriptor": null,
    "tax_code": null,
    "type": "service",
    "unit_label": null,
    "updated": 1697844815,
    "url": null,
    "price": {
      "id": "price_1O3DqOGzrCvGnkrSgyXzYKAU",
      "object": "price",
      "active": true,
      "billing_scheme": "per_unit",
      "created": 1697789648,
      "currency": "usd",
      "custom_unit_amount": null,
      "livemode": false,
      "lookup_key": null,
      "metadata": {},
      "nickname": null,
      "product": "prod_Oqvh8kupUP5etR",
      "recurring": null,
      "tax_behavior": "unspecified",
      "tiers_mode": null,
      "transform_quantity": null,
      "type": "one_time",
      "unit_amount": 45000,
      "unit_amount_decimal": "45000",
    },
  },
  //   {
  //     "id": "prod_OqvTgdbxiN1QnK",
  //     "object": "product",
  //     "active": true,
  //     "attributes": [],
  //     "created": 1697788769,
  //     "default_price": "price_1O3DcEGzrCvGnkrSPnW2ozEK",
  //     "description":
  //       "Upgrade your kitchen with our modern cabinet design. Clean lines, sleek hardware, and ample storage make this the perfect addition to your culinary space, combining style and functionality seamlessly.",
  //     "features": [],
  //     "images": [
  //       "https://files.stripe.com/links/MDB8YWNjdF8xTnJES3JHenJDdkdua3JTfGZsX3Rlc3RfV2dSOE1saVBESzBsQzBnS0thYjhmYUY500Q6QqC88X",
  //     ],
  //     "livemode": false,
  //     "metadata": {
  //       "dining": "cabinets",
  //     },
  //     "name": "Terea Kitchen Cabinet",
  //     "package_dimensions": null,
  //     "shippable": null,
  //     "statement_descriptor": null,
  //     "tax_code": null,
  //     "type": "service",
  //     "unit_label": null,
  //     "updated": 1697844592,
  //     "url": null,
  //     "price": {
  //       "id": "price_1O3DcEGzrCvGnkrSPnW2ozEK",
  //       "object": "price",
  //       "active": true,
  //       "billing_scheme": "per_unit",
  //       "created": 1697788770,
  //       "currency": "usd",
  //       "custom_unit_amount": null,
  //       "livemode": false,
  //       "lookup_key": null,
  //       "metadata": {},
  //       "nickname": null,
  //       "product": "prod_OqvTgdbxiN1QnK",
  //       "recurring": null,
  //       "tax_behavior": "unspecified",
  //       "tiers_mode": null,
  //       "transform_quantity": null,
  //       "type": "one_time",
  //       "unit_amount": 45000,
  //       "unit_amount_decimal": "45000",
  //     },
  //   },
  //   {
  //     "id": "prod_OqvNmsoUL59tld",
  //     "object": "product",
  //     "active": true,
  //     "attributes": [],
  //     "created": 1697788452,
  //     "default_price": "price_1O3DX6GzrCvGnkrSilUTviCD",
  //     "description":
  //       "Elevate your kitchen with our sleek and space-efficient modern wall cabinet. Its minimalist design offers ample storage while adding a contemporary touch to your culinary space.",
  //     "features": [],
  //     "images": [
  //       "https://files.stripe.com/links/MDB8YWNjdF8xTnJES3JHenJDdkdua3JTfGZsX3Rlc3RfQmQyMUdrdXlHWmpUVjFHQTlEM3NPQlFn00xvYxJIqK",
  //     ],
  //     "livemode": false,
  //     "metadata": {
  //       "dining": "cabinets",
  //     },
  //     "name": "Carlsbad Cabinets",
  //     "package_dimensions": null,
  //     "shippable": null,
  //     "statement_descriptor": null,
  //     "tax_code": null,
  //     "type": "service",
  //     "unit_label": null,
  //     "updated": 1697844482,
  //     "url": null,
  //     "price": {
  //       "id": "price_1O3DX6GzrCvGnkrSilUTviCD",
  //       "object": "price",
  //       "active": true,
  //       "billing_scheme": "per_unit",
  //       "created": 1697788452,
  //       "currency": "usd",
  //       "custom_unit_amount": null,
  //       "livemode": false,
  //       "lookup_key": null,
  //       "metadata": {},
  //       "nickname": null,
  //       "product": "prod_OqvNmsoUL59tld",
  //       "recurring": null,
  //       "tax_behavior": "unspecified",
  //       "tiers_mode": null,
  //       "transform_quantity": null,
  //       "type": "one_time",
  //       "unit_amount": 30000,
  //       "unit_amount_decimal": "30000",
  //     },
  //   },
  //   {
  //     "id": "prod_OqvMQd1qtbpx1i",
  //     "object": "product",
  //     "active": true,
  //     "attributes": [],
  //     "created": 1697788358,
  //     "default_price": "price_1O3DVbGzrCvGnkrSwbzs8FLp",
  //     "description":
  //       "Introducing our modern 4-seater small dining table – a perfect blend of style and functionality. Its sleek design and compact size make it ideal for intimate gatherings, offering a contemporary touch to your dining area.",
  //     "features": [
  //       {
  //         "name": "6 Seater",
  //       },
  //     ],
  //     "images": [
  //       "https://files.stripe.com/links/MDB8YWNjdF8xTnJES3JHenJDdkdua3JTfGZsX3Rlc3RfMGlUUzdOTzFtanMzeWhCTk4zTXRiZ3Ji00ARTBBGdl",
  //     ],
  //     "livemode": false,
  //     "metadata": {
  //       "dining": "table",
  //     },
  //     "name": "Carlsbad Dining Table",
  //     "package_dimensions": null,
  //     "shippable": null,
  //     "statement_descriptor": null,
  //     "tax_code": null,
  //     "type": "service",
  //     "unit_label": null,
  //     "updated": 1697851832,
  //     "url": null,
  //     "price": {
  //       "id": "price_1O3DVbGzrCvGnkrSwbzs8FLp",
  //       "object": "price",
  //       "active": true,
  //       "billing_scheme": "per_unit",
  //       "created": 1697788359,
  //       "currency": "usd",
  //       "custom_unit_amount": null,
  //       "livemode": false,
  //       "lookup_key": null,
  //       "metadata": {},
  //       "nickname": null,
  //       "product": "prod_OqvMQd1qtbpx1i",
  //       "recurring": null,
  //       "tax_behavior": "unspecified",
  //       "tiers_mode": null,
  //       "transform_quantity": null,
  //       "type": "one_time",
  //       "unit_amount": 70000,
  //       "unit_amount_decimal": "70000",
  //     },
  //   },
  //   {
  //     "id": "prod_OqoBHCUTJcmqGf",
  //     "object": "product",
  //     "active": true,
  //     "attributes": [],
  //     "created": 1697761687,
  //     "default_price": "price_1O36ZPGzrCvGnkrSjtctvUIM",
  //     "description":
  //       "Elevate your workspace with our modern wall office cabinet. Sleek, minimalist design meets functionality, providing ample storage and organization while adding a contemporary touch to your home office or workspace.",
  //     "features": [],
  //     "images": [
  //       "https://files.stripe.com/links/MDB8YWNjdF8xTnJES3JHenJDdkdua3JTfGZsX3Rlc3RfVlNqaTF6akZMckoxTnV5NVhVcWtQRmlT00NeGYNZYT",
  //     ],
  //     "livemode": false,
  //     "metadata": {},
  //     "name": "Maximo Office Cabinet",
  //     "package_dimensions": null,
  //     "shippable": null,
  //     "statement_descriptor": null,
  //     "tax_code": null,
  //     "type": "service",
  //     "unit_label": null,
  //     "updated": 1697844874,
  //     "url": null,
  //     "price": {
  //       "id": "price_1O36ZPGzrCvGnkrSjtctvUIM",
  //       "object": "price",
  //       "active": true,
  //       "billing_scheme": "per_unit",
  //       "created": 1697761687,
  //       "currency": "usd",
  //       "custom_unit_amount": null,
  //       "livemode": false,
  //       "lookup_key": null,
  //       "metadata": {},
  //       "nickname": null,
  //       "product": "prod_OqoBHCUTJcmqGf",
  //       "recurring": null,
  //       "tax_behavior": "unspecified",
  //       "tiers_mode": null,
  //       "transform_quantity": null,
  //       "type": "one_time",
  //       "unit_amount": 15000,
  //       "unit_amount_decimal": "15000",
  //     },
];
